name: "feature_preprocessing"
description: "Preprocessing features for ML training."
cloud: anyscale_k8s_gcp_cloud
cluster_env: eoakes-nightly-jobs:5
entrypoint: python preprocess.py
runtime_env:
  working_dir: https://github.com/edoakes/ray_jobs_demo/archive/refs/heads/master.zip
